Repository WootingKb/wooting-macros, pull requests merged in 2023-12, with the labels that each got.

#192 fix: search result visible even with 0 macros
  src/components/overview/MacroList.tsx
Labels: enhancement

#181 Library/update
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src/components/macroview/rightPanel/editForms/OpenEventForm.tsx
  src/components/settings/SettingsLeftPanel.tsx
  src/constants/externalLinks.ts
  src/constants/utils.ts
  src/contexts/applicationContext.tsx
  src/hooks/useRecordingSequence.ts
  src/hooks/useRecordingTrigger.ts
  tsconfig.json
  wooting-macro-backend/Cargo.lock
  wooting-macro-backend/Cargo.toml
  yarn.lock
Labels: dependencies

#174 Mouse 1 Passthrough
  wooting-macro-backend/src/lib.rs
Labels: bug

#137 Feature/delay
  wooting-macro-backend/src/lib.rs
Labels: feature, good first issue
